### ISSUE TITLE
A prop event indicating whether the images have loaded.

### ISSUE THREAD

**Issue by dmahajan980** [nevestuan/react-tridi#11]
This is a great open-source library for 360 degrees product visualization. I have been using this in multiple projects and for the most part, this works flawlessly. However, there are multiple cases where the need for a prop event (a callback function passed as prop and registered internally by the library as a listener to a specific event) for image loading becomes essential (such as `onImagesLoad`).

For example, this library could be used in a product customizer that offers a variety of customization options (such as [a sofa customizer](https://www.eq3.com/ca/en/product/ck3916sfy0etp0134iw99zld5/living/seating/apartment-sofas/reverie-apartment-sofa-fabric-apartment-sofa-h0825-black-sand?ck2z1tqkr032x01069s41q58z=ck3hx6rln0l1m0118nyza4kh5&ck3hx6rm50l1p0118f49bn94o=ck3hx6rmk0l1q011826xhtmly&ck3hx6rm50l1p0118f49bn94o%7CPrimaryColour=H1099&ck3hx6rm50l1p0118f49bn94o%7CBaseLeg=H0825)). When the user selects a new option (such as a different color), it results in a server request for a new set of images. A spinner can be shown for the duration the images load. However, to achieve such a behavior, there needs to be an event listener that gets triggered when the images load completely.

Would love to hear more about your suggestions and the feasibility of this feature.

**Comment by nevestuan** [comment]
Thank you for your feedback. It is a good idea. I will find a way to add that prop in.

**Comment by AksAman** [comment]
> This is a great open-source library for 360 degrees product visualization. I have been using this in multiple projects and for the most part, this works flawlessly. However, there are multiple cases where the need for a prop event (a callback function passed as prop and registered internally by the library as a listener to a specific event) for image loading becomes essential (such as `onImagesLoad`).
> 
> For example, this library could be used in a product customizer that offers a variety of customization options (such as [a sofa customizer](https://www.eq3.com/ca/en/product/ck3916sfy0etp0134iw99zld5/living/seating/apartment-sofas/reverie-apartment-sofa-fabric-apartment-sofa-h0825-black-sand?ck2z1tqkr032x01069s41q58z=ck3hx6rln0l1m0118nyza4kh5&ck3hx6rm50l1p0118f49bn94o=ck3hx6rmk0l1q011826xhtmly&ck3hx6rm50l1p0118f49bn94o%7CPrimaryColour=H1099&ck3hx6rm50l1p0118f49bn94o%7CBaseLeg=H0825)). When the user selects a new option (such as a different color), it results in a server request for a new set of images. A spinner can be shown for the duration the images load. However, to achieve such a behavior, there needs to be an event listener that gets triggered when the images load completely.
> 
> Would love to hear more about your suggestions and the feasibility of this feature.

This will be definitely a great addon to the library. Currently there is no feedback of whether the images have been loaded all or not. 
+1 from my side too.

**Comment by nevestuan** [comment]
@AksAman thank you so much for your help to add this feature. A new version has been released with it.
