### ISSUE TITLE
hint text doesn't work

### ISSUE THREAD

**Issue by 3adel-bassiony** [nevestuan/react-tridi#55]
I tried to add those props `hintOnStartUp`  & `hintText` but nothing appear when adding them.
Did I miss something or there is an issue in hint text?

**Comment by nevestuan** [comment]
Could you provide a sample code?

I tried on my demo repo, it still works. You may check it here: https://github.com/nevestuan/react-tridi-demo

**Comment by 3adel-bassiony** [comment]
Thank you, I found the issue, it's a misspelling issue in your documentation, it should be `hintOnStartup` not `hintOnStartUp`

<img width="878" alt="Screen Shot 2022-02-13 at 12 49 48 PM" src="https://user-images.githubusercontent.com/81669622/153749765-13c7f002-b519-4a8e-8049-cfd97c9d3228.png">

**Comment by nevestuan** [comment]
Thank you for pointing it out. I will update the documentation accordingly.
